swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger REST API Emergency
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api/emergency/"

# Paths supported by the server application
paths:
  /feu:
    get:
      operationId: "feu.read_all"
      tags:
        - "Feu"
      summary: "Read the list of feu"
      description: "Read the list of feu"
      responses:
        200:
          description: "Successful read feu list operation"
          schema:
            type: "array"
            items:
              properties:
                id:
                  type: "integer"
                position:
                  type: "object"
                  properties: 
                    x: 
                      type: "integer"
                    y:
                      type: "integer"
                intensite:
                  type: "integer"
    post:
      operationId: "feu.create"
      tags:
        - "Feu"
      summary: "Create a feu"
      description: "Create a feu"
      parameters:
        - name: feu
          in: body
          description: Feu to create
          required: True
          schema:
            type: object
            properties:
              id:
                type: "integer"
                description: Identifiant du feu calcule
              position:
                type: "object"
                properties: 
                  x: 
                    type: "integer"
                  y:
                    type: "integer"
                description: Coord du feu calcule
              intensite:
                type: "integer"
                description: "Intensite du feu calcule"
      responses:
        201:
          description: "Successful create feu"
          schema:
            type: "array"
            items:
              properties:
                id:
                  type: "integer"
                position:
                  type: "object"
                  properties: 
                    x: 
                      type: "integer"
                    y:
                      type: "integer"
                intensite:
                  type: "integer"
    put:
      operationId: feu.update
      tags:
        - Feu
      summary: Update all feu
      description: Update all feu
      parameters:
        - name: feux
          in: body
          description: Feux to update
          required: True
          schema:
            type: array
            items:
              properties:
                id:
                  type: "integer"
                position:
                  type: "object"
                  properties: 
                    x: 
                      type: "integer"
                    y:
                      type: "integer"
                intensite:
                  type: "integer"
      responses:
        200:
          description: Successfully updated feu
          schema:
            type: array
            items:
              properties:
                id:
                  type: "integer"
                position:
                  type: "object"
                  properties: 
                    x: 
                      type: "integer"
                    y:
                      type: "integer"
                intensite:
                  type: "integer"

    delete:
      operationId: feu.delete
      tags:
        - Feu
      summary: Delete a feu from the feu list
      description: Delete a feu
      responses:
        200:
          description: Successfully deleted a feu

    
  /capteur:
    get:
      operationId: "capteur.read_all"
      tags:
        - "Capteur"
      summary: "Read the list of capteur"
      description: "Read the list of capteur"
      responses:
        200:
          description: "Successful read capteur list operation"
          schema:
            type: "array"
            items:
              properties:
                id:
                  type: "integer"
                position:
                  type: "object"
                  properties: 
                    x: 
                      type: "integer"
                    y:
                      type: "integer"
                range:
                  type: "integer"
                intensite:
                  type: "integer"
    post:
      operationId: "capteur.create"
      tags:
        - "Capteur"
      summary: "Create a capteur"
      description: "Create a capteur"
      parameters:
        - name: capteur
          in: body
          description: Capteur to create
          required: True
          schema:
            type: object
            properties:
              id:
                type: integer
                description: Id of the capteur
              position:
                type: "object"
                properties: 
                  x: 
                    type: "integer"
                  y:
                    type: "integer"
                description: Coord x and y
              range:
                type: integer
                description: range de detection
              intensite:
                type: integer
                description: intensite de detection
      responses:
        201:
          description: "Successful created capteur"
          schema:
            type: "array"
            items:
              properties:
                id:
                  type: "integer"
                position:
                  type: "object"
                  properties: 
                    x: 
                      type: "integer"
                    y:
                      type: "integer"
                range:
                  type: "integer"
                intensite:
                  type: "integer"
    put:
      operationId: capteur.update
      tags:
        - Capteur
      summary: Update all capteurs
      description: Update all capteurs
      parameters:
        - name: capteurs
          in: body
          description: Capteurs to update
          required: True
          schema:
            type: array
            items:
              properties:
                id:
                  type: "integer"
                position:
                  type: "object"
                  properties: 
                    x: 
                      type: "integer"
                    y:
                      type: "integer"
                range:
                  type: "integer"
                intensite:
                  type: "integer"
      responses:
        200:
          description: Successfully updated capteur
          schema:
            type: array
            items:
              properties:
                id:
                  type: "integer"
                position:
                  type: "object"
                  properties: 
                    x: 
                      type: "integer"
                    y:
                      type: "integer"
                range:
                  type: "integer"
                intensite:
                  type: "integer"
    delete:
      operationId: capteur.delete
      tags:
        - Capteur
      summary: Delete all capteur from the database
      description: Delete all capteur
      responses:
        200:
          description: Successfully deleted all capteur