swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger REST API Emergency
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api/emergency/"

# Paths supported by the server application
paths:
  /feu:
    get:
      operationId: "feu.read_all"
      tags:
        - "Feu"
      summary: "The feu data structure supported by the server application"
      description: "Read the list of feu"
      responses:
        200:
          description: "Successful read feu list operation"
          schema:
            type: "array"
            items:
              properties:
                id:
                  type: "integer"
                position:
                  type: "object"
                intensite:
                  type: "integer"
    post:
      operationId: "feu.create"
      tags:
        - "Feu"
      summary: "The people data structure supported by the server application"
      description: "Read the list of feu"
      parameters:
        - name: feu
          in: body
          description: Feu to create
          required: True
          schema:
            type: object
            properties:
              id:
                type: integer
                description: First name of person to create
              position:
                type: object
                description: Last name of person to create
              intensite:
                type: integer
                description: Last name of person to create
      responses:
        201:
          description: "Successful read people list operation"
          schema:
            type: "array"
            items:
              properties:
                id:
                  type: "integer"
                position:
                  type: "object"
                intensite:
                  type: "integer"
    delete:
      operationId: feu.delete
      tags:
        - Feu
      summary: Delete a feu from the feu list
      description: Delete a feu
      responses:
        200:
          description: Successfully deleted a feu

    
  /capteur:
    get:
      operationId: "capteur.read_all"
      tags:
        - "Capteur"
      summary: "The people data structure supported by the server application"
      description: "Read the list of people"
      responses:
        200:
          description: "Successful read people list operation"
          schema:
            type: "array"
            items:
              properties:
                id:
                  type: "integer"
                position:
                  type: "object"
                range:
                  type: "integer"
                intensite:
                  type: "integer"
    post:
      operationId: "capteur.create"
      tags:
        - "Capteur"
      summary: "The people data structure supported by the server application"
      description: "Read the list of people"
      parameters:
        - name: capteur
          in: body
          description: Capteur to create
          required: True
          schema:
            type: object
            properties:
              id:
                type: integer
                description: First name of person to create
              position:
                type: object
                description: Last name of person to create
              range:
                type: integer
                description: Last name of person to create
              intensite:
                type: integer
                description: Last name of person to create
      responses:
        201:
          description: "Successful read people list operation"
          schema:
            type: "array"
            items:
              properties:
                id:
                  type: "integer"
                position:
                  type: "object"
                range:
                  type: "integer"
                intensite:
                  type: "integer"
    put:
      operationId: capteur.update
      tags:
        - Capteur
      summary: Update a capteur
      description: Update a capteur
      parameters:
        - name: capteurs
          in: body
          description: Capteurs to update
          required: True
          schema:
            type: array
            items:
              properties:
                id:
                  type: "integer"
                position:
                  type: "object"
                range:
                  type: "integer"
                intensite:
                  type: "integer"
      responses:
        200:
          description: Successfully updated capteur
          schema:
            properties:
              person_id:
                type: string
                description: Id of the person in the database
              fname:
                type: string
                description: First name of the person
              lname:
                type: string
                description: Last name of the person
              timestamp:
                type: string
                description: Creation/Update timestamp of the person record
    delete:
      operationId: capteur.delete
      tags:
        - Capteur
      summary: Delete all capteur from the database
      description: Delete all capteur
      responses:
        200:
          description: Successfully deleted all capteur